name: Build

on:
  push:
    branches:
      - "dev"
    paths:
      - "SimpleToolkit.UI.Models**"
  pull_request:
    branches:
      - "dev"
      - "main"
    paths:
      - "SimpleToolkit.UI.Models**"

jobs:
  build:
    name: Build
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Create NuGet package
        run: dotnet pack -c Debug --output ./